test: Add magic comment
Because the following error occurred in Ruby 1.9:

===============================================================================
Error: test_command(CommandTest)
ArgumentError: invalid byte sequence in US-ASCII
/home/travis/build/myokoym/feedcellar/test/test-command.rb:63:in `scan'
/home/travis/build/myokoym/feedcellar/test/test-command.rb:63:in `test_command'
    60:     io = StringIO.new(s)
    61:     $stdout = io
    62:     @@command.export
 => 63:     assert_equal(1, s.scan(/<opml/).size)
    64:     assert_equal(3, s.scan(/<outline/).size)
    65:     $stdout = STDOUT
    66:

===============================================================================